Info in <testing_macro.py>: /eos/user/t/tcritchl/xgBOOST/trained_models12/tmva_signal_40GeV_1e-2.rootdoes not exist
