python3: can't open file '/afs/cern.ch/work/t/tcritchl/FCCAnalyses_local/xgboost/parallel_scripts/testing_macro.py': [Errno 2] No such file or directory
